### ISSUE TITLE
Use of reserved constant name 'DEFAULT'

### ISSUE THREAD

**Issue by SilvanLaroo** [dealer4dealer/magento-2-pricelist#3]
Hi,

We face some issues in your module. In this file: https://github.com/dealer4dealer/magento-2-pricelist/blob/master/Helper/Codes/CustomerConfig.php a constant named 'DEFAULT' is defined. A constant named 'DEFAULT' should never be used, default is a reserved name in PHP. Because of this, we have some issues during synchronization of customers. 

Regards,
Silvan

**Comment by HenriNijborg** [comment]
Resolved in release 0.3.5
